name: build-windows-x64

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 默认就是 64 位 Python（这里显式写清楚）
      - name: Setup Python x64
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }
          pip install pyinstaller

      - name: Build exe (x64)
        run: |
          pyinstaller ^
            --onefile ^
            --clean ^
            --name myapp ^
            copy_file_to.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-windows-x64
          path: dist/*.exe
